# -*- coding: utf-8 -*-
"""Day4 Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m00BnFakNdyZDbSKmoWfBG2QA_ifTy5Q
"""

#Q1)Python program to check leap year.
year=int(input("Enter a year:"))
if(year%4==0 and year % 100 !=0) or (year % 400==0):
  print("It is a Leap Year")
else:
  print("It is not a Leap Year")

#Q2)Python Program to find the Largest Among Three Numbers.
a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
c=int(input("Enter third number:"))

if a>=b and a>=c:
  print(a,"is the largest number")
elif b>=a and b>=c:
  print(b,"is the largest number")
  print(c,"is the largest number")

#Q3)Python Program to check if a Number is Positive ,Negative,or 0
num=float(input("Enter a number:"))
if num>0:
 print("Positive number")
elif num<0:
  print("Negative number")
else:
  print("Zero")

#Q4)A toy vendor supplies three types of toys: Battery Based Toys, Key-based Toys, and Electrical Charging Based Toys. The vendor gives a discount of
#10% on orders for battery-based toys if the order is for more than Rs. 1000. On orders of more than Rs. 100 for key-based toys, a discount of 5% is given, and a discount of 10% is given on orders for electrical charging based toys of value more than Rs. 500. Assume that the numeric codes 1,2 and 3 are used for battery based toys, key-based toys, and electrical charging based toys respectively. Write a program that reads the product code and the order amount and prints out the net amount that the customer is required to pay after the discount.
print("1: Battery Based Toys")
print("2: Key-bsed Toys")
print("3: Electrical Charging Based Toys")

product_code=int(input("Enter product code(1,2, or 3):"))
amount=float(input("Enter the order amount:"))

if product_code==1 and amount>1000:
  discount=amount*0.10
elif product_code==2 and amount>100:
  discount=amount*0.05
elif product_code==3 and amount>500:
  discount=amount*0.10
else:
  discount=0

net_amount=amount-discount
print(f"Discount applied:Rs.{discount:}")
print(f"Net amount to pay :Rs.{net_amount}")

#Q5)transport company charges the fare according to following table:
 distance=float(input("Enter distance in km:"))
 if distance<=50:
  fare=distance*8
 elif distance<=100:
  fare=distance*10
 else:
  fare=distance*12
 print(f"Total fare:Rs.{fare}")