# -*- coding: utf-8 -*-
"""Day 2 lab operators .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdYiEeEI6yS2keg6e7KT8Judv55GEyUA
"""

#Q1)Calculate the multiplication and sum of two numbers
x=3
y=5
print("Addition=",x+y,"Multiplication=",x*y)

#Q2)Declare two variables and print that which variable is largest using ternary operators.
a=10
b=20
print("a is greater"if a>b else "b is greater")

#Q3)Python program to convert the temperature in degree centigrade to Fahreneit.
celsius=float(input("Enter temperature in Celsius:"))
fahrenheit=(celsius*9/5)+32
print(f"{celsius}C degree is equal to {fahrenheit}F")

#Q4)Python program to find the area of a triangle whose sides are given.
b=3
h=4
a=1/2
print("Area of triangle=",a*b*h)